### ISSUE TITLE
Fichier .sql

### ISSUE THREAD

**Issue by RtcSmocky** [Povers/AmaryllisV2---Ace-3-Medical---Save-vehicule-and-position#1]
Salut Povers, j'aimerai apprendre un peu comment fonctionne ton système de sauvegarde des véhicules et j'aurai voulu savoir si c'est possible d'avoir ton fichier .sql de ta base de données pour voir les requêtes ?
Merci d'avance :)

**Comment by Povers** [comment]
Bonsoir,

Pour le système de sauvegarde des véhicules, tout le code est côté serveur et vu que c'est moi qui l'ai fait, il est commenté en détails
Pour la structure, elle est désormais disponible.
